name: DB Wake

on:
  schedule:
    - cron: "*/25 * * * *"

jobs:
  curl_job:
    runs-on: ubuntu-latest

    steps:
      - name: Executar comando curl
        run: |
          curl lucasgonc.vercel.app/send/wake -v
