name: DB Wake

on:
  schedule:
    - cron: "*/10 * * * *"

jobs:
  curl_job:
    runs-on: ubuntu-latest

    steps:
      - name: Executar comando curl
        run: |
          curl lucasgonc.onrender.com/send/wake -v
