name: Wake DB

on:
  schedule:
    - cron: "0 0 * * *"

jobs:
  curl_job:
    runs-on: ubuntu-latest

    steps:
      - name: Executar comando curl
        run: |
          curl https://lucasgonc.vercel.app/send/wake
